print("Welcome to the tip calculator!")
total_bill = float(input("What was the total bill? $"))
tip_percentage = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
tip_amount = total_bill * (tip_percentage / 100)
amount_per_person = float(input("How many people to split the bill? "))
print("Each person should pay: $" + str(round((total_bill + tip_amount) / amount_per_person, 2)))